<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "account_type".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\Account[] $accounts
 * @property string $aliasModel
 */
abstract class AccountType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'account_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccounts()
    {
        return $this->hasMany(\common\models\Account::className(), ['account_type_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\AccountTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\AccountTypeQuery(get_called_class());
    }


}
