<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "category".
 *
 * @property integer $id
 * @property string $name
 * @property integer $category_type_id
 * @property integer $icon_id
 * @property integer $color_id
 *
 * @property \common\models\CategoryType $categoryType
 * @property \common\models\Color $color
 * @property \common\models\Icon $icon
 * @property \common\models\Transaction[] $transactions
 * @property string $aliasModel
 */
abstract class Category extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'category_type_id', 'icon_id', 'color_id'], 'required'],
            [['category_type_id', 'icon_id', 'color_id'], 'integer'],
            [['name'], 'string', 'max' => 80],
            [['category_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\CategoryType::className(), 'targetAttribute' => ['category_type_id' => 'id']],
            [['color_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Color::className(), 'targetAttribute' => ['color_id' => 'id']],
            [['icon_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Icon::className(), 'targetAttribute' => ['icon_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'category_type_id' => 'Kind of Category',
            'icon_id' => 'Icon',
            'color_id' => 'Color',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'category_type_id' => 'Kind of Category',
            'icon_id' => 'Icon',
            'color_id' => 'Color',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryType()
    {
        return $this->hasOne(\common\models\CategoryType::className(), ['id' => 'category_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getColor()
    {
        return $this->hasOne(\common\models\Color::className(), ['id' => 'color_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIcon()
    {
        return $this->hasOne(\common\models\Icon::className(), ['id' => 'icon_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransactions()
    {
        return $this->hasMany(\common\models\Transaction::className(), ['category_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\TransactionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\TransactionQuery(get_called_class());
    }


}
