<?php

// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\Category;
use common\models\CategoryTypeQuery;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "category_type".
 *
 * @property integer $id
 * @property string $name
 *
 * @property Category[] $categories
 * @property string $aliasModel
 */
abstract class CategoryType extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::class, ['category_type_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return CategoryTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CategoryTypeQuery(get_called_class());
    }
}
