<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "color".
 *
 * @property integer $id
 * @property string $name
 * @property string $value
 *
 * @property \common\models\Account[] $accounts
 * @property \common\models\Category[] $categories
 * @property string $aliasModel
 */
abstract class Color extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'color';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'value'], 'required'],
            [['name'], 'string', 'max' => 20],
            [['value'], 'string', 'max' => 6]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'value' => 'HEX Value',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'value' => 'HEX Value',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccounts()
    {
        return $this->hasMany(\common\models\Account::className(), ['color_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(\common\models\Category::className(), ['color_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ColorQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ColorQuery(get_called_class());
    }


}
