<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "currency".
 *
 * @property integer $id
 * @property string $abbreviation
 * @property string $name
 *
 * @property \common\models\Account[] $accounts
 * @property \common\models\Transaction[] $transactions
 * @property string $aliasModel
 */
abstract class Currency extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'currency';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['abbreviation'], 'required'],
            [['abbreviation'], 'string', 'max' => 3],
            [['name'], 'string', 'max' => 60]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'abbreviation' => 'Abbreviation',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccounts()
    {
        return $this->hasMany(\common\models\Account::className(), ['default_currency' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransactions()
    {
        return $this->hasMany(\common\models\Transaction::className(), ['currency_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CurrencyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CurrencyQuery(get_called_class());
    }


}
