<?php

// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\Account;
use common\models\Category;
use common\models\IconImage;
use common\models\IconQuery;
use common\models\IconType;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "icon".
 *
 * @property integer $id
 * @property integer $icon_type_id
 * @property integer $icon_image_id
 *
 * @property Account[] $accounts
 * @property Category[] $categories
 * @property IconImage $iconImage
 * @property IconType $iconType
 * @property string $aliasModel
 */
abstract class Icon extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'icon';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['icon_type_id', 'icon_image_id'], 'required'],
            [['icon_type_id', 'icon_image_id'], 'integer'],
            [['icon_image_id'], 'exist', 'skipOnError' => true,
                'targetClass' => IconImage::class,
                'targetAttribute' => ['icon_image_id' => 'id']],
            [['icon_type_id'], 'exist', 'skipOnError' => true,
                'targetClass' => IconType::class,
                'targetAttribute' => ['icon_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'icon_type_id' => 'Type',
            'icon_image_id' => 'Image',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'icon_type_id' => 'Icon type could be a filename or a glyphicon name',
            'icon_image_id' => 'Icon image or glyph name',
        ]);
    }

    /**
     * @return ActiveQuery
     */
    public function getAccounts()
    {
        return $this->hasMany(Account::class, ['icon_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::class, ['icon_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getIconImage()
    {
        return $this->hasOne(IconImage::class, ['id' => 'icon_image_id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getIconType()
    {
        return $this->hasOne(IconType::class, ['id' => 'icon_type_id']);
    }

    /**
     * @inheritdoc
     * @return IconQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new IconQuery(get_called_class());
    }
}
