<?php

// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\Icon;
use common\models\IconImageQuery;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "icon_image".
 *
 * @property integer $id
 * @property string $name
 *
 * @property Icon[] $icons
 * @property string $aliasModel
 */
abstract class IconImage extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'icon_image';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getIcons()
    {
        return $this->hasMany(Icon::class, ['icon_image_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return IconImageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new IconImageQuery(get_called_class());
    }
}
